return {
	["aoe_bombard_muzzle"] = {
		flash = {
			air = true,
			ground = true,
			water = true,
			class = [[CBitmapMuzzleFlame]],
			count = 1,
			properties = {
				colormap = [[1.0 0.72 0.28 0.9   0.9 0.25 0.05 0.35   0 0 0 0]],
				dir = [[dir]],
				frontoffset = 0,
				fronttexture = [[muzzlefront]],
				length = 32,
				sidetexture = [[muzzleside]],
				size = 18,
				sizegrowth = 0.4,
				ttl = 7,
			},
		},
		smoke = {
			air = true,
			ground = true,
			water = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			properties = {
				airdrag = 0.90,
				colormap = [[0.38 0.35 0.31 0.38   0.16 0.15 0.14 0.18   0 0 0 0]],
				directional = true,
				emitrot = 3,
				emitrotspread = 9,
				emitvector = [[dir]],
				gravity = [[0, 0.012, 0]],
				numparticles = 5,
				particlelife = 18,
				particlelifespread = 6,
				particlesize = 5,
				particlesizespread = 2,
				particlespeed = 1.4,
				particlespeedspread = 0.8,
				pos = [[0, 0, 0]],
				sizegrowth = 0.45,
				sizemod = 1,
				texture = [[smoketrail]],
			},
		},
	},
	["aoe_bombard_smoke"] = {
		smoke = {
			air = true,
			ground = true,
			water = true,
			underwater = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			properties = {
				airdrag = 0.92,
				colormap = [[0.32 0.30 0.27 0.28   0.18 0.17 0.16 0.16   0 0 0 0]],
				directional = false,
				emitrot = 0,
				emitrotspread = 18,
				emitvector = [[0, 1, 0]],
				gravity = [[0, 0.015, 0]],
				numparticles = 1,
				particlelife = 12,
				particlelifespread = 4,
				particlesize = 3,
				particlesizespread = 1.5,
				particlespeed = 0.25,
				particlespeedspread = 0.15,
				pos = [[0, 0, 0]],
				sizegrowth = 0.35,
				sizemod = 1,
				texture = [[smoketrail]],
			},
		},
	},
	-- Keep an empty custom generator so Recoil does not substitute its standard
	-- impact effect. AOE Projectile Effect rendering owns the visual; WeaponDef
	-- hit sounds and all native damage/explosion gameplay remain unchanged.
	["aoe_bombard_impact"] = {},
}
