return {
	["aoe_bombard_muzzle"] = {
		flash = {
			air = true,
			ground = true,
			water = true,
			class = [[CBitmapMuzzleFlame]],
			count = 1,
			properties = {
				colormap = [[1.0 0.72 0.28 0.9   0.9 0.25 0.05 0.35   0 0 0 0]],
				dir = [[dir]],
				frontoffset = 0,
				fronttexture = [[muzzlefront]],
				length = 32,
				sidetexture = [[muzzleside]],
				size = 18,
				sizegrowth = 0.4,
				ttl = 7,
			},
		},
		smoke = {
			air = true,
			ground = true,
			water = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			properties = {
				airdrag = 0.90,
				colormap = [[0.38 0.35 0.31 0.38   0.16 0.15 0.14 0.18   0 0 0 0]],
				directional = true,
				emitrot = 3,
				emitrotspread = 9,
				emitvector = [[dir]],
				gravity = [[0, 0.012, 0]],
				numparticles = 5,
				particlelife = 18,
				particlelifespread = 6,
				particlesize = 5,
				particlesizespread = 2,
				particlespeed = 1.4,
				particlespeedspread = 0.8,
				pos = [[0, 0, 0]],
				sizegrowth = 0.45,
				sizemod = 1,
				texture = [[smoketrail]],
			},
		},
	},
	["aoe_bombard_smoke"] = {
		smoke = {
			air = true,
			ground = true,
			water = true,
			underwater = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			properties = {
				airdrag = 0.92,
				colormap = [[0.32 0.30 0.27 0.28   0.18 0.17 0.16 0.16   0 0 0 0]],
				directional = false,
				emitrot = 0,
				emitrotspread = 18,
				emitvector = [[0, 1, 0]],
				gravity = [[0, 0.015, 0]],
				numparticles = 1,
				particlelife = 12,
				particlelifespread = 4,
				particlesize = 3,
				particlesizespread = 1.5,
				particlespeed = 0.25,
				particlespeedspread = 0.15,
				pos = [[0, 0, 0]],
				sizegrowth = 0.35,
				sizemod = 1,
				texture = [[smoketrail]],
			},
		},
	},
	["aoe_bombard_impact"] = {
		groundflash = {
			circlealpha = 0.35,
			circlegrowth = 3,
			flashalpha = 0.75,
			flashsize = 48,
			ttl = 12,
			color = { 1.0, 0.55, 0.20 },
		},
		flash = {
			air = true,
			ground = true,
			water = true,
			underwater = true,
			class = [[CHeatCloudProjectile]],
			count = 1,
			properties = {
				heat = 8,
				heatfalloff = 1.2,
				maxheat = 12,
				pos = [[0, 6, 0]],
				size = 16,
				sizegrowth = 5,
				texture = [[flare]],
			},
		},
		debris = {
			air = true,
			ground = true,
			water = true,
			class = [[CSimpleParticleSystem]],
			count = 1,
			properties = {
				airdrag = 0.88,
				colormap = [[0.55 0.36 0.18 0.65   0.18 0.12 0.07 0.25   0 0 0 0]],
				directional = true,
				emitrot = 35,
				emitrotspread = 25,
				emitvector = [[0, 1, 0]],
				gravity = [[0, -0.08, 0]],
				numparticles = 10,
				particlelife = 18,
				particlelifespread = 8,
				particlesize = 3,
				particlesizespread = 2,
				particlespeed = 2,
				particlespeedspread = 2,
				pos = [[0, 3, 0]],
				sizegrowth = -0.03,
				sizemod = 1,
				texture = [[randdots]],
			},
		},
	},
}
