local modOptions = Spring.GetModOptions()
local attackCannotMoveValue = tostring(modOptions.aoe_attack_cannot_move or "true"):lower()
local attackCannotMove =
	attackCannotMoveValue == "1" or
	attackCannotMoveValue == "true" or
	attackCannotMoveValue == "yes" or
	attackCannotMoveValue == "on"

return {
	UnitDefs = {
		aoe_archer = {
			name = "AOE Gameplay Archer",
			description = "Native Recoil Gameplay Unit with an AOE2 render appearance",
			objectName = "fir_tree_smallest.s3o",
			script = "aoe_archer.lua",
			explodeAs = "NOWEAPON",
			selfDestructAs = "NOWEAPON",
			category = "LAND",
			footprintX = 2,
			footprintZ = 2,
			collisionVolumeType = "CylY",
			collisionVolumeScales = "24 60 24",
			maxDamage = 100,
			buildCostMetal = 1,
			buildTime = 1,
			power = 1,
			mass = 50,
			canMove = true,
			canGuard = true,
			canPatrol = true,
				canStop = true,
				canAttack = true,
				canFireControl = true,
				corpse = "aoe_archer_dead",
			movementClass = "AOE2_TEST_UNIT",
			speed = 90,
			maxAcc = 0.15,
			maxDec = 0.30,
			turnRate = 1200,
			turnInPlace = true,
			stopToAttack = true,
			attackCannotMove = attackCannotMove,
			attackStartSpeedThreshold = 0.3,
			upright = true,
			sightDistance = 500,
			aoeArmor = {
				melee = 0,
				pierce = 0,
				infantry = 0,
			},
			aoeUpgradeTags = { "archer", "infantry" },
				customParams = {
				aoe2_unit_id = "u_arc_archer",
				aoe2_scale = "1.0",
				aoe2_ground_offset = "0.0",
				aoe2_player_color = "team",
				aoe2_hide_native_model = "true",
				aoe2_animation_speed = "1.0",
				-- AOE DAT weapon_offset=(0, 0.5, 1.5). The base conversion
				-- (right=x*60, up=z*30, forward=y*60) gives (0, 45, 30).
				-- Manual all-direction calibration adds an archer-specific
				-- (0, 10.5, 0) correction. Keep that correction explicit until
				-- another ranged unit validates a reusable vertical rule.
				aoe2_aim_local = "0 30 0",
				aoe2_weapon1_muzzle_local = "0 55.5 30",
				aoe2_weapon1_forward_local = "0 0 1",
				},
				weapons = {
					{ name = "AOE_ARROW" },
				},
			},
		aoe_camel_scout = {
			name = "AOE Camel Scout",
			description = "Native Recoil melee gameplay unit with an AOE2 render appearance",
			objectName = "fir_tree_smallest.s3o",
			script = "aoe_camel_scout.lua",
			explodeAs = "NOWEAPON",
			selfDestructAs = "NOWEAPON",
			category = "LAND",
			footprintX = 2,
			footprintZ = 2,
			collisionVolumeType = "CylY",
			-- DAT collision_size=(0.25, 0.25, 2.0). Keep the validated
			-- horizontal*60 and vertical*30 AOE-to-Recoil conversion explicit.
			collisionVolumeScales = "30 60 30",
			maxDamage = 120,
			buildCostMetal = 1,
			buildTime = 1,
			power = 1,
			mass = 80,
			canMove = true,
			canGuard = true,
			canPatrol = true,
			canStop = true,
			canAttack = true,
			canFireControl = true,
			corpse = "aoe_camel_scout_dead",
			movementClass = "AOE2_TEST_UNIT",
			speed = 105,
			maxAcc = 0.18,
			maxDec = 0.30,
			turnRate = 1200,
			turnInPlace = true,
			stopToAttack = true,
			attackCannotMove = attackCannotMove,
			attackStartSpeedThreshold = 0.3,
			upright = true,
			sightDistance = 500,
			aoeArmor = {
				melee = 1,
				pierce = 1,
				cavalry = 0,
			},
			aoeUpgradeTags = { "cavalry" },
			customParams = {
				aoe2_unit_id = "u_cam_camel_scout",
				aoe2_scale = "1.0",
				aoe2_ground_offset = "0.0",
				aoe2_player_color = "team",
				aoe2_hide_native_model = "true",
				aoe2_animation_speed = "1.0",
				-- Melee has no projectile muzzle. Supplying the body-centre
				-- weapon anchor keeps native range and facing checks independent
				-- of the hidden placeholder model's pieces.
				aoe2_aim_local = "0 30 0",
				aoe2_weapon1_muzzle_local = "0 30 0",
				aoe2_weapon1_forward_local = "0 0 1",
			},
			weapons = {
				{ name = "AOE_CAMEL_SCOUT_MELEE" },
			},
		},
		aoe_afri_tower_age2 = {
			name = "AOE African Age II Tower",
			description = "Native Recoil CBuilding with an AOE2 tower appearance",
			objectName = "fir_tree_smallest.s3o",
			script = "aoe_afri_tower_age2.lua",
			explodeAs = "NOWEAPON",
			selfDestructAs = "NOWEAPON",
			category = "BUILDING LAND",
			footprintX = 2,
			footprintZ = 2,
			yardMap = "oooo",
			levelGround = true,
			collisionVolumeType = "CylY",
			-- The x2 tower sprite occupies approximately 141 x 268 world units at
			-- Aoe2UnitPixelsToWorld=0.55.  Keep a small visual margin while making
			-- the native hit volume match the tower shaft rather than the old tree.
			collisionVolumeScales = "120 240 120",
			maxDamage = 800,
			buildCostMetal = 1,
			buildTime = 1,
			power = 1,
			mass = 100000,
			canMove = false,
			canAttack = true,
			canFireControl = true,
			corpse = "aoe_afri_tower_age2_rubble",
			sightDistance = 650,
			upright = true,
			customParams = {
				aoe2_building_id = "b_afri_tower_age2",
				aoe2_scale = "1.0",
				aoe2_ground_offset = "0.0",
				aoe2_player_color = "team",
				aoe2_hide_native_model = "true",
				-- DAT weapon_offset=(0,1,5), converted by the validated shared
				-- profile (right=x*60, up=z*30, forward=y*60), then calibrated
				-- in the building anchor preview (+41 Recoil world units on up).
				aoe2_aim_local = "0 60 0",
				-- Keep the enlarged 240-unit collision cylinder on the ground
				-- without changing the tower's validated target aim point.
				aoe2_collision_local = "0 120 0",
				aoe2_weapon1_muzzle_local = "0 191 60",
				aoe2_weapon1_forward_local = "0 0 1",
			},
			weapons = {
				{ name = "AOE_TOWER_ARROW" },
			},
		},
		aoe_west_castle_age3 = {
			name = "AOE Western Age III Castle",
			description = "Native Recoil CBuilding with an AOE2 western castle appearance",
			objectName = "fir_tree_smallest.s3o",
			script = "aoe_west_castle_age3.lua",
			explodeAs = "NOWEAPON",
			selfDestructAs = "NOWEAPON",
			category = "BUILDING LAND",
			-- The source DAT collision radii are (2, 2) and the display sprite is
			-- about 385 world units wide at Aoe2UnitPixelsToWorld=0.55. Keep the
			-- pathing footprint and the native hit volume consistent with that size.
			footprintX = 6,
			footprintZ = 6,
			yardMap = "oooooooooooooooooooooooooooooooooooo",
			levelGround = true,
			collisionVolumeType = "Box",
			collisionVolumeScales = "400 330 400",
			-- Source DAT Unit 82 (CSTL) has 4800 hit points, 11 LOS, range 8,
			-- reload 2 s and graphic_displacement=(0, 1, 4). The uncalibrated
			-- shared conversion is (right=x*60, up=z*30, front=y*60).
			maxDamage = 4800,
			buildCostMetal = 1,
			buildTime = 1,
			power = 1,
			mass = 500000,
			canMove = false,
			canAttack = true,
			canFireControl = true,
			corpse = "aoe_west_castle_age3_rubble",
			sightDistance = 660,
			upright = true,
			customParams = {
				aoe2_building_id = "b_west_castle_age3",
				aoe2_scale = "1.0",
				aoe2_ground_offset = "0.0",
				aoe2_player_color = "team",
				aoe2_hide_native_model = "true",
				aoe2_aim_local = "0 120 0",
				aoe2_collision_local = "0 165 0",
				aoe2_weapon1_muzzle_local = "0 120 60",
				aoe2_weapon1_forward_local = "0 0 1",
			},
			weapons = {
				{ name = "AOE_CASTLE_ARROW" },
			},
		},
		},
	FeatureDefs = {
		aoe_archer_dead = {
			description = "AOE archer corpse gameplay host",
			object = "fir_tree_smallest.s3o",
			blocking = true,
			reclaimable = true,
			resurrectable = 0,
			smokeTime = 0,
			health = 100,
			metal = 1,
			footprintX = 2,
			footprintZ = 2,
			customParams = {
				aoe2_corpse = "true",
				aoe2_unit_id = "u_arc_archer",
				aoe2_death_frames = "30",
				aoe2_corpse_hold_frames = "120",
				aoe2_corpse_fade_frames = "60",
			},
		},
		aoe_camel_scout_dead = {
			description = "AOE camel scout corpse gameplay host",
			object = "fir_tree_smallest.s3o",
			blocking = true,
			reclaimable = true,
			resurrectable = 0,
			smokeTime = 0,
			health = 120,
			metal = 1,
			footprintX = 2,
			footprintZ = 2,
			customParams = {
				aoe2_corpse = "true",
				aoe2_unit_id = "u_cam_camel_scout",
				aoe2_death_frames = "45",
				aoe2_corpse_hold_frames = "120",
				aoe2_corpse_fade_frames = "60",
			},
		},
		aoe_afri_tower_age2_rubble = {
			description = "AOE tower rubble gameplay host",
			object = "fir_tree_smallest.s3o",
			blocking = true,
			reclaimable = true,
			resurrectable = 0,
			smokeTime = 0,
			health = 800,
			metal = 1,
			footprintX = 2,
			footprintZ = 2,
			customParams = {
				aoe2_corpse = "true",
				aoe2_building_id = "b_afri_tower_age2",
				aoe2_corpse_hold_frames = "450",
				aoe2_corpse_fade_frames = "150",
			},
		},
		aoe_west_castle_age3_rubble = {
			description = "AOE western castle rubble gameplay host",
			object = "fir_tree_smallest.s3o",
			blocking = true,
			reclaimable = true,
			resurrectable = 0,
			smokeTime = 0,
			health = 4800,
			metal = 1,
			footprintX = 6,
			footprintZ = 6,
			customParams = {
				aoe2_corpse = "true",
				aoe2_building_id = "b_west_castle_age3",
				aoe2_corpse_hold_frames = "450",
				aoe2_corpse_fade_frames = "150",
			},
		},
	},
	WeaponDefs = {
		noweapon = {
			name = "No death explosion",
			weaponType = "Melee",
			areaOfEffect = 0,
			impulseFactor = 0,
			impulseBoost = 0,
			damage = { default = 0 },
		},
		aoe_arrow = {
			name = "Native test arrow",
			weaponType = "Cannon",
			areaOfEffect = 8,
			impactOnly = true,
			impulseFactor = 0,
			impulseBoost = 0,
			range = 550,
			reloadtime = 2,
			windup = 0.5,
			attackRecoveryTime = 0.5,
			accuracy = 0,
			sprayAngle = 0,
			targetMoveError = 0,
			weaponVelocity = 400,
			gravityAffected = true,
			-- Require the unit chassis (and therefore the directional sprite) to
			-- face the target before firing. 1820 legacy angle units is about 10°.
			turret = false,
			tolerance = 1820,
			avoidFriendly = false,
			collideFriendly = false,
			avoidFeature = false,
			collideFeature = false,
			damage = { default = 5 },
			aoeDamage = {
				pierce = 5,
			},
			aoeUpgradeTags = { "archer" },
			customParams = {
				aoe2_projectile_id = "p_arrow",
				aoe2_projectile_scale = "1.0",
			},
		},
		aoe_tower_arrow = {
			name = "Native tower arrow",
			weaponType = "Cannon",
			areaOfEffect = 8,
			impactOnly = true,
			impulseFactor = 0,
			impulseBoost = 0,
			-- African Age II Tower source combat uses Projectile Unit 504,
			-- pierce damage 3, max range 8 and a two-second reload.
			range = 480,
			reloadtime = 2,
			windup = 0.5,
			attackRecoveryTime = 0.5,
			accuracy = 0,
			sprayAngle = 0,
			targetMoveError = 0,
			weaponVelocity = 400,
			gravityAffected = true,
			-- Buildings use StaticMoveType and cannot turn their chassis. Keep the
			-- archer's forward-only weapon unchanged; this separate WeaponDef lets
			-- the tower acquire and fire at enemies in every horizontal direction.
			turret = true,
			avoidFriendly = false,
			collideFriendly = false,
			avoidFeature = false,
			collideFeature = false,
			damage = { default = 3 },
			aoeDamage = {
				pierce = 3,
			},
			aoeUpgradeTags = { "archer" },
			customParams = {
				-- Projectile Units 504 and 746 both use the same AoE2DE Graphic
				-- 3402 (p_arrow_x2.sld), so this shared cache id avoids duplicate
				-- GPU textures while retaining the gameplay source identity.
				aoe2_projectile_id = "p_arrow",
				aoe2_projectile_scale = "1.0",
				aoe2_projectile_source_unit_id = "504",
				aoe2_projectile_source_graphic_id = "3402",
			},
		},
		aoe_castle_arrow = {
			name = "Native castle arrow",
			weaponType = "Cannon",
			areaOfEffect = 8,
			impactOnly = true,
			impulseFactor = 0,
			impulseBoost = 0,
			-- Source Castle DAT max_range=8.0 converted with the existing
			-- 60 world-units-per-AOE-range profile. Keep one native weapon slot:
			-- that lets the AOE bridge drive one AttackA animation while Recoil
			-- owns the five-arrow temporal burst.
			range = 960,
			reloadtime = 2,
			windup = 0.5,
			burst = 5,
			burstRate = 0.12,
			attackRecoveryTime = 0.5,
			accuracy = 0,
			sprayAngle = 0,
			targetMoveError = 0,
			weaponVelocity = 400,
			gravityAffected = true,
			turret = true,
			avoidFriendly = false,
			collideFriendly = false,
			avoidFeature = false,
			collideFeature = false,
			damage = { default = 11 },
			aoeDamage = {
				pierce = 11,
			},
			aoeUpgradeTags = { "castle" },
			customParams = {
				aoe2_projectile_id = "p_arrow",
				aoe2_projectile_scale = "1.0",
				aoe2_projectile_source_unit_id = "746",
				aoe2_projectile_source_graphic_id = "3402",
			},
		},
		aoe_camel_scout_melee = {
			name = "Native camel scout melee attack",
			weaponType = "Melee",
			areaOfEffect = 0,
			canAttackGround = false,
			impulseFactor = 0,
			impulseBoost = 0,
			range = 32,
			reloadtime = 2,
			-- The manifest releases on AttackA frame 10 of 30 at 30 FPS.
			-- Recovery covers the remaining 20 frames so Gameplay owns the
			-- complete one-second attack animation interval.
			windup = 0.3333333333,
			attackRecoveryTime = 0.6666666667,
			targetBorder = 1,
			cylinderTargeting = 1,
			turret = false,
			tolerance = 1820,
			damage = { default = 10 },
			aoeDamage = {
				melee = 7,
				cavalry = 2,
			},
			aoeUpgradeTags = { "cavalry" },
		},
	},
	ArmorDefs = {},
	MoveDefs = {
		{
			name = "AOE2_TEST_UNIT",
			footprintX = 2,
			footprintZ = 2,
			maxSlope = 36,
			maxWaterDepth = 12,
			crushStrength = 10,
		},
	},
}
