return {
	aoe_fixed_test_camera = {
		name = "AOE fixed test camera",
		desc = "Use the shared fixed camera in AOE gameplay test scenes",
		type = "bool",
		def = false,
	},
	aoe_orthographic_test_camera = {
		name = "AOE orthographic test camera",
		desc = "Use a true orthographic projection with the shared fixed AOE test camera",
		type = "bool",
		def = false,
	},
	aoe_building_test = {
		name = "AOE building test",
		desc = "Spawn four directional native AOE towers with debug anchor and collision overlays",
		type = "bool",
		def = false,
	},
	aoe_team_towers = {
		name = "AOE formation towers",
		desc = "Place one native AOE tower behind each standard battle formation",
		type = "bool",
		def = false,
	},
	aoe_anchor_calibration = {
		name = "AOE anchor calibration",
		desc = "Spawn the static all-direction AOE remote-unit anchor calibration scene",
		type = "bool",
		def = false,
	},
	aoe_anchor_calibration_spacing = {
		name = "AOE calibration spacing",
		desc = "World-space spacing between calibration units",
		type = "number",
		def = 260,
		min = 64,
		max = 1024,
		step = 1,
	},
	aoe_anchor_calibration_ground_attack = {
		name = "AOE calibration ground attack",
		desc = "Make all 16 calibration units attack the ground directly ahead using native CMD.ATTACK",
		type = "bool",
		def = false,
	},
	aoe_melee_calibration = {
		name = "AOE melee calibration",
		desc = "Spawn the all-direction Camel Scout melee range and collision calibration scene",
		type = "bool",
		def = false,
	},
	aoe_melee_battle = {
		name = "AOE melee battle",
		desc = "Spawn two native Camel Scout teams and issue CMD.FIGHT",
		type = "bool",
		def = false,
	},
	aoe_melee_calibration_spacing = {
		name = "AOE melee calibration spacing",
		desc = "World-space spacing between the 16 melee calibration pairs",
		type = "number",
		def = 260,
		min = 160,
		max = 1024,
		step = 1,
	},
	aoe_melee_target_distance = {
		name = "AOE melee target distance",
		desc = "Centre distance used by the in-range static melee calibration",
		type = "number",
		def = 44,
		min = 30,
		max = 128,
		step = 1,
	},
	aoe_melee_approach_distance = {
		name = "AOE melee approach distance",
		desc = "Centre distance used when testing native close-in movement",
		type = "number",
		def = 96,
		min = 48,
		max = 256,
		step = 1,
	},
	aoe_melee_damage = {
		name = "AOE melee calibration damage",
		desc = "Allow real damage in the melee calibration tool",
		type = "bool",
		def = true,
	},
	aoe_melee_start_auto_attack = {
		name = "AOE melee start attacking",
		desc = "Start the calibration pairs in repeat-attack mode for automated regression runs",
		type = "bool",
		def = false,
	},
	aoe_melee_team_a_count = {
		name = "AOE melee Team A size",
		desc = "Camel Scout count for Team A in the melee battle test",
		type = "number",
		def = 16,
		min = 1,
		max = 1000,
		step = 1,
	},
	aoe_melee_team_b_count = {
		name = "AOE melee Team B size",
		desc = "Camel Scout count for Team B in the melee battle test",
		type = "number",
		def = 16,
		min = 1,
		max = 1000,
		step = 1,
	},
	aoe_camel_scout_fraction = {
		name = "AOE Camel Scout fraction",
		desc = "Fraction of each standard battle formation occupied by Camel Scouts at the enemy-facing front",
		type = "number",
		def = 0,
		min = 0,
		max = 1,
		step = 0.01,
	},
	aoe_position_diagnostics = {
		name = "AOE position diagnostics",
		desc = "Log bounded position timelines when attackCannotMove units make short reverse movements",
		type = "bool",
		def = true,
	},
	aoe_position_diagnostic_samples = {
		name = "AOE position diagnostic samples",
		desc = "Maximum number of evenly distributed units sampled per team",
		type = "number",
		def = 64,
		min = 1,
		max = 128,
		step = 1,
	},
	aoe_attack_cannot_move = {
		name = "AOE strict stationary attack",
		desc = "Enable attackCannotMove on the test archer; disable for ordinary-movement regression",
		type = "bool",
		def = true,
	},
	aoe_explicit_move_regression = {
		name = "AOE explicit Move regression",
		desc = "Issue native CMD.MOVE during sampled Windup and Recovery phases and report pass/fail",
		type = "bool",
		def = false,
	},
	aoe_armor_upgrade_test = {
		name = "AOE armor upgrade test",
		desc = "Apply the configured AOE attack and armor upgrades after both test teams spawn",
		type = "bool",
		def = false,
	},
	aoe_castle_rapid_fire_upgrade_test = {
		name = "AOE castle rapid-fire technology test",
		desc = "Apply castle_rapid_fire: upgrade native castle arrow bursts from 5 to 10 shots",
		type = "bool",
		def = false,
	},
}
